server {
    listen       80;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html;

    # Fallback de SPA: todas as rotas voltam para o index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache para assets com hash no nome
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
